### ISSUE TITLE
按照说明开启后并不会生效

### ISSUE THREAD

**Issue by CoolTowel** [theme-next/theme-next-han#1]
使用的Hexo版本：3.7.1
使用的NexT版本：6.1.0
按照README文档中的三个步骤开启后并没有达到预期的效果，如：汉字－西文混排间隙。

**Comment by wangjiezhe** [comment]
@CoolTowel 混排间隙是 pangu.js 控制的，参见 [theme-next/theme-next-pangu](https://github.com/theme-next/theme-next-pangu)。
